<?php

use Illuminate\Database\Seeder;
use App\Models\Masters\CsvOutputSetting;

class InitCsvOutputSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ["5", "会計部門集計_計上売上CSV", "1", "受注番号", "orders.id", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "2", "ご注文日", "orders.created_at", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "3", "受注ステータス", "orders.order_status_id", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "4", "顧客ID", "orders.customer_id", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "5", "お届け先名(姓)", "shippings.name01", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "6", "お届け先名(名)", "shippings.name02", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "7", "小計", "orders.subtotal + orders.subtotal_tax as subtotal", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "8", "値引", "orders.discount", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "9", "送料", "orders.delivery_fee + orders.delivery_fee_tax as delivery_fee", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "10", "手数料", "orders.payment_method_fee + orders.payment_method_fee_tax as payment_method_fee", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "11", "消費税額", "orders.payment_total_tax", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "12", "支払金額", "orders.payment_total + orders.payment_total_tax as payment_total", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "13", "発送日", "shippings.shipped_timestamp", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "14", "配送指定日", "shippings.requested_delivery_date", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "15", "キャンセル日時", "orders.canceled_timestamp", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "16", "まとめ配送", "order_bundle_shippings.parent_order_id", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "17", "伝票番号", "shippings.delivery_slip_num", "TRUE",],
            ["5", "会計部門集計_計上売上CSV", "18", "支払方法", "orders.payment_method_name", "TRUE",],
            [
                "5",
                "会計部門集計_計上売上CSV",
                "19",
                "割引分類",
                "case WHEN orders.order_count_of_customer=1 THEN '初回' WHEN (orders.order_count_of_customer>1 and orders.periodic_order_id >0) THEN  '定期' WHEN (orders.order_count_of_customer>1 and orders.periodic_order_id is null) THEN 'リピート' END as order_count_of_customer",
                "TRUE",
            ],
            ["6", "会計部門集計_キャンセルCSV", "1", "受注番号", "orders.id", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "2", "ご注文日", "orders.created_at", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "3", "受注ステータス", "orders.order_status_id", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "4", "顧客ID", "orders.customer_id", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "5", "お届け先名(姓)", "shippings.name01", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "6", "お届け先名(名)", "shippings.name02", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "7", "小計", "orders.subtotal + orders.subtotal_tax as subtotal", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "8", "値引", "orders.discount", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "9", "送料", "orders.delivery_fee + orders.delivery_fee_tax as delivery_fee", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "10", "手数料", "orders.payment_method_fee + orders.payment_method_fee_tax as payment_method_fee", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "11", "消費税額", "orders.payment_total_tax", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "12", "支払金額", "orders.payment_total + orders.payment_total_tax as payment_total", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "13", "発送日", "shippings.shipped_timestamp", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "14", "配送指定日", "shippings.requested_delivery_date", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "15", "キャンセル日時", "orders.canceled_timestamp", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "16", "まとめ配送", "order_bundle_shippings.parent_order_id", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "17", "伝票番号", "shippings.delivery_slip_num", "TRUE",],
            ["6", "会計部門集計_キャンセルCSV", "18", "支払方法", "orders.payment_method_name", "TRUE",],
            [
                "6",
                "会計部門集計_キャンセルCSV",
                "19",
                "割引分類",
                "case WHEN orders.order_count_of_customer=1 THEN '初回' WHEN (orders.order_count_of_customer>1 and orders.periodic_order_id >0) THEN  '定期' WHEN (orders.order_count_of_customer>1 and orders.periodic_order_id is null) THEN 'リピート' END as order_count_of_customer",
                "TRUE",
            ],
            ["7", "卸集計CSV", "1", "受注番号", "orders.id", "TRUE",],
            ["7", "卸集計CSV", "2", "ご注文日", "orders.created_at", "TRUE",],
            ["7", "卸集計CSV", "3", "受注ステータス", "orders.order_status_id", "TRUE",],
            ["7", "卸集計CSV", "4", "顧客ID", "orders.customer_id", "TRUE",],
            ["7", "卸集計CSV", "5", "お届け先名(姓)", "shippings.name01", "TRUE",],
            ["7", "卸集計CSV", "6", "お届け先名(名)", "shippings.name02", "TRUE",],
            ["7", "卸集計CSV", "7", "小計", "orders.subtotal + orders.subtotal_tax as subtotal", "TRUE",],
            ["7", "卸集計CSV", "8", "値引", "orders.discount", "TRUE",],
            ["7", "卸集計CSV", "9", "送料", "orders.delivery_fee + orders.delivery_fee_tax as delivery_fee", "TRUE",],
            ["7", "卸集計CSV", "10", "手数料", "orders.payment_method_fee + orders.payment_method_fee_tax as payment_method_fee", "TRUE",],
            ["7", "卸集計CSV", "11", "消費税額", "orders.payment_total_tax", "TRUE",],
            ["7", "卸集計CSV", "12", "支払金額", "orders.payment_total + orders.payment_total_tax as payment_total", "TRUE",],
            ["7", "卸集計CSV", "13", "発送日", "shippings.shipped_timestamp", "TRUE",],
            ["7", "卸集計CSV", "14", "配送指定日", "shippings.requested_delivery_date", "TRUE",],
            ["7", "卸集計CSV", "15", "キャンセル日時", "orders.canceled_timestamp", "TRUE",],
            ["7", "卸集計CSV", "16", "まとめ配送", "order_bundle_shippings.parent_order_id", "TRUE",],
            ["7", "卸集計CSV", "17", "伝票番号", "shippings.delivery_slip_num", "TRUE",],
            ["7", "卸集計CSV", "18", "支払方法", "orders.payment_method_name", "TRUE",],
            [
                "7",
                "卸集計CSV",
                "19",
                "割引分類",
                "case WHEN orders.order_count_of_customer=1 THEN '初回' WHEN (orders.order_count_of_customer>1 and orders.periodic_order_id >0) THEN  '定期' WHEN (orders.order_count_of_customer>1 and orders.periodic_order_id is null) THEN 'リピート' END as order_count_of_customer",
                "TRUE",
            ],
            ["8", "年代別集計CSV", "1", "受注番号", "orders.id", "TRUE",],
            ["8", "年代別集計CSV", "2", "ご注文日", "orders.created_at", "TRUE",],
            ["8", "年代別集計CSV", "3", "受注ステータス", "orders.order_status_id", "TRUE",],
            ["8", "年代別集計CSV", "4", "顧客ID", "orders.customer_id", "TRUE",],
            ["8", "年代別集計CSV", "5", "お届け先名(姓)", "shippings.name01", "TRUE",],
            ["8", "年代別集計CSV", "6", "お届け先名(名)", "shippings.name02", "TRUE",],
            ["8", "年代別集計CSV", "7", "小計", "orders.subtotal + orders.subtotal_tax as subtotal", "TRUE",],
            ["8", "年代別集計CSV", "8", "値引", "orders.discount", "TRUE",],
            ["8", "年代別集計CSV", "9", "送料", "orders.delivery_fee + orders.delivery_fee_tax as delivery_fee", "TRUE",],
            ["8", "年代別集計CSV", "10", "手数料", "orders.payment_method_fee + orders.payment_method_fee_tax as payment_method_fee", "TRUE",],
            ["8", "年代別集計CSV", "11", "消費税額", "orders.payment_total_tax", "TRUE",],
            ["8", "年代別集計CSV", "12", "支払金額", "orders.payment_total + orders.payment_total_tax as payment_total", "TRUE",],
            ["8", "年代別集計CSV", "13", "発送日", "shippings.shipped_timestamp", "TRUE",],
            ["8", "年代別集計CSV", "14", "配送指定日", "shippings.requested_delivery_date", "TRUE",],
            ["8", "年代別集計CSV", "15", "キャンセル日時", "orders.canceled_timestamp", "TRUE",],
            ["8", "年代別集計CSV", "16", "まとめ配送", "order_bundle_shippings.parent_order_id", "TRUE",],
            ["8", "年代別集計CSV", "17", "伝票番号", "shippings.delivery_slip_num", "TRUE",],
            ["8", "年代別集計CSV", "18", "支払方法", "orders.payment_method_name", "TRUE",],
            [
                "8",
                "年代別集計CSV",
                "19",
                "割引分類",
                "case WHEN orders.order_count_of_customer=1 THEN '初回' WHEN (orders.order_count_of_customer>1 and orders.periodic_order_id >0) THEN  '定期' WHEN (orders.order_count_of_customer>1 and orders.periodic_order_id is null) THEN 'リピート' END ",
                "TRUE",
            ],
            ["9", "支払い方法別集計CSV", "1", "受注番号", "orders.id", "TRUE",],
            ["9", "支払い方法別集計CSV", "2", "ご注文日", "orders.created_at", "TRUE",],
            ["9", "支払い方法別集計CSV", "3", "受注ステータス", "orders.order_status_id", "TRUE",],
            ["9", "支払い方法別集計CSV", "4", "顧客ID", "orders.customer_id", "TRUE",],
            ["9", "支払い方法別集計CSV", "5", "お届け先名(姓)", "shippings.name01", "TRUE",],
            ["9", "支払い方法別集計CSV", "6", "お届け先名(名)", "shippings.name02", "TRUE",],
            ["9", "支払い方法別集計CSV", "7", "小計", "orders.subtotal + orders.subtotal_tax as subtotal", "TRUE",],
            ["9", "支払い方法別集計CSV", "8", "値引", "orders.discount", "TRUE",],
            ["9", "支払い方法別集計CSV", "9", "送料", "orders.delivery_fee + orders.delivery_fee_tax as delivery_fee", "TRUE",],
            ["9", "支払い方法別集計CSV", "10", "手数料", "orders.payment_method_fee + orders.payment_method_fee_tax as payment_method_fee", "TRUE",],
            ["9", "支払い方法別集計CSV", "11", "消費税額", "orders.payment_total_tax", "TRUE",],
            ["9", "支払い方法別集計CSV", "12", "支払金額", "orders.payment_total + orders.payment_total_tax as payment_total", "TRUE",],
            ["9", "支払い方法別集計CSV", "13", "発送日", "shippings.shipped_timestamp", "TRUE",],
            ["9", "支払い方法別集計CSV", "14", "配送指定日", "shippings.requested_delivery_date", "TRUE",],
            ["9", "支払い方法別集計CSV", "15", "キャンセル日時", "orders.canceled_timestamp", "TRUE",],
            ["9", "支払い方法別集計CSV", "16", "まとめ配送", "order_bundle_shippings.parent_order_id", "TRUE",],
            ["9", "支払い方法別集計CSV", "17", "伝票番号", "shippings.delivery_slip_num", "TRUE",],
            ["9", "支払い方法別集計CSV", "18", "支払方法", "orders.payment_method_name", "TRUE",],
            [
                "9",
                "支払い方法別集計CSV",
                "19",
                "割引分類",
                "case WHEN orders.order_count_of_customer=1 THEN '初回' WHEN (orders.order_count_of_customer>1 and orders.periodic_order_id >0) THEN  '定期' WHEN (orders.order_count_of_customer>1 and orders.periodic_order_id is null) THEN 'リピート' END  as order_count_of_customer",
                "TRUE",
            ],
            ["1", "顧客管理CSV", "1", "顧客ID", "customers.id", "TRUE",],
            ["1", "顧客管理CSV", "2", "お名前(姓)", "customers.name01", "TRUE",],
            ["1", "顧客管理CSV", "3", "お名前(名)", "customers.name02", "TRUE",],
            ["1", "顧客管理CSV", "4", "お名前(フリガナ・姓)", "customers.kana01", "TRUE",],
            ["1", "顧客管理CSV", "5", "お名前(フリガナ・名)", "customers.kana02", "TRUE",],
            ["1", "顧客管理CSV", "6", "郵便番号", "customers.zipcode", "TRUE",],
            ["1", "顧客管理CSV", "7", "都道府県", "prefectures.name as prefecture_name", "TRUE",],
            ["1", "顧客管理CSV", "8", "住所1", "customers.address01", "TRUE",],
            ["1", "顧客管理CSV", "9", "住所2", "customers.address02", "TRUE",],
            ["1", "顧客管理CSV", "10", "E-MAIL", "customers.email", "TRUE",],
            ["1", "顧客管理CSV", "11", "誕生日", "customers.birthday", "TRUE",],
            ["1", "顧客管理CSV", "12", "初回購入日", "customers.first_buy_date", "TRUE",],
            ["1", "顧客管理CSV", "13", "最終購入日", "customers.last_buy_date", "TRUE",],
            ["1", "顧客管理CSV", "14", "購入回数", "customers.buy_times", "TRUE",],
            ["1", "顧客管理CSV", "15", "登録日時", "customers.created_at", "TRUE",],
            ["1", "顧客管理CSV", "16", "更新日時", "customers.updated_at", "TRUE",],
            ["1", "顧客管理CSV", "17", "家電禁止", "customers.no_phone_call_flag", "TRUE",],
            ["1", "顧客管理CSV", "18", "広告番号", "customers.advertising_media_code", "TRUE",],
            [
                "1",
                "顧客管理CSV",
                "19",
                "SHOPメモ",
                "regexp_replace((select string_agg(tmp_string, '') from (select (to_char(created_at,'YYYYMMDD HH24：MI ') || note) as tmp_string from shop_memos where shop_memos.customer_id = customers.id ORDER BY created_at desc) as tmp_memo ), '\(\r\n|\r|\n|\t\)', ' ', 'g') as shop_memo",
                "TRUE",
            ],
            ["1", "顧客管理CSV", "20", "電話番号1", "customers.phone_number01", "TRUE",],
            ["1", "顧客管理CSV", "21", "配送要望", "customers.requests_for_delivery", "FALSE",],
            ["1", "顧客管理CSV", "22", "電話番号2", "customers.phone_number02", "FALSE",],
            ["1", "顧客管理CSV", "23", "購入金額", "customers.buy_total", "FALSE",],
            ["1", "顧客管理CSV", "24", "購入本数", "customers.buy_volume", "FALSE",],
            ["1", "顧客管理CSV", "25", "メルマガ", "customers.mail_magazine_flag", "FALSE",],
            ["1", "顧客管理CSV", "26", "DM", "customers.dm_flag", "FALSE",],
            ["1", "顧客管理CSV", "27", "卸", "customers.wholesale_flag", "FALSE",],
            ["1", "顧客管理CSV", "28", "ポートフォリオ", "pfm_statuses.name as pfm_statuse_name", "FALSE",],
            ["1", "顧客管理CSV", "29", "登録経路", "registration_routes.name as registration_route_name", "FALSE",],
            ["1", "顧客管理CSV", "30", "顧客種別", "customers.customer_status_id", "FALSE",],
            ["2", "受注管理CSV", "1", "注文番号", "orders.id", "TRUE",],
            ["2", "受注管理CSV", "2", "顧客ID", "orders.customer_id", "TRUE",],
            ["2", "受注管理CSV", "3", "要望等", "orders.message_from_customer", "TRUE",],
            ["2", "受注管理CSV", "4", "お名前(姓)", "orders.name01", "TRUE",],
            ["2", "受注管理CSV", "5", "お名前(名)", "orders.name02", "TRUE",],
            ["2", "受注管理CSV", "6", "お名前(フリガナ・姓)", "orders.kana01", "TRUE",],
            ["2", "受注管理CSV", "7", "お名前(フリガナ名)", "orders.kana02", "TRUE",],
            ["2", "受注管理CSV", "8", "電話番号1", "orders.phone_number01", "TRUE",],
            ["2", "受注管理CSV", "9", "電話番号2", "orders.phone_number02", "TRUE",],
            ["2", "受注管理CSV", "10", "郵便番号", "orders.zipcode", "TRUE",],
            ["2", "受注管理CSV", "11", "都道府県", "prefectures.name as prefecture_name", "TRUE",],
            ["2", "受注管理CSV", "12", "住所１", "orders.address01", "TRUE",],
            ["2", "受注管理CSV", "13", "住所２", "orders.address02", "TRUE",],
            ["2", "受注管理CSV", "14", "小計", "orders.subtotal + orders.subtotal_tax as subtotal", "TRUE",],
            ["2", "受注管理CSV", "15", "値引き", "orders.discount", "TRUE",],
            ["2", "受注管理CSV", "16", "送料", "orders.delivery_fee + orders.delivery_fee_tax as delivery_fee", "TRUE",],
            [
                "2",
                "受注管理CSV",
                "17",
                "お支払い合計",
                "orders.payment_total + orders.payment_total_tax as payment_total",
                "TRUE",
            ],
            ["2", "受注管理CSV", "18", "支払い方法", "orders.payment_method_name", "TRUE",],
            ["2", "受注管理CSV", "19", "メールアドレス", "orders.email", "TRUE",],
            [
                "2",
                "受注管理CSV",
                "20",
                "手数料",
                "orders.payment_method_fee + orders.payment_method_fee_tax as payment_method_fee",
                "TRUE",
            ],
            ["2", "受注管理CSV", "21", "合計", "orders.total + orders.total_tax as total", "FALSE",],
            ["2", "受注管理CSV", "22", "対応状況", "order_statuses.name as order_status_name", "TRUE",],
            ["2", "受注管理CSV", "23", "注文日時", "orders.created_at", "TRUE",],
            ["2", "受注管理CSV", "24", "発送日時", "shippings.shipped_timestamp", "TRUE",],
            [
                "2",
                "受注管理CSV",
                "25",
                "SHOPメモ",
                "regexp_replace((select string_agg(tmp_string, '') from (select (to_char(created_at,'YYYYMMDD HH24：MI ') || note) as tmp_string from shop_memos where shop_memos.order_id = orders.id ORDER BY created_at desc) as tmp_memo ), '\(\r\n|\r|\n|\t\)', ' ', 'g') as shop_memo",
                "TRUE",
            ],
            ["2", "受注管理CSV", "26", "配送要望", "orders.requests_for_delivery", "FALSE",],
            ["2", "受注管理CSV", "27", "適用税率", "orders.tax_rate", "FALSE",],
            [
                "2",
                "受注管理CSV",
                "28",
                "定価小計",
                "orders.catalog_price_subtotal + orders.catalog_price_subtotal_tax as catalog_price_subtotal",
                "FALSE",
            ],
            [
                "2",
                "受注管理CSV",
                "29",
                "定価との差額",
                "orders.discount_from_catalog_price + orders.discount_from_catalog_price_tax as discount_from_catalog_price",
                "FALSE",
            ],
            ["2", "受注管理CSV", "30", "配送業者名", "orders.delivery_name", "FALSE",],
            ["2", "受注管理CSV", "31", "売上計上日時", "orders.sales_timestamp", "FALSE",],
            ["2", "受注管理CSV", "32", "キャンセル日時", "orders.canceled_timestamp", "FALSE",],
            ["2", "受注管理CSV", "33", "定期ID", "orders.periodic_order_id", "FALSE",],
            ["2", "受注管理CSV", "34", "定期回", "orders.periodic_count", "FALSE",],
            ["2", "受注管理CSV", "35", "購入回（キャンセル除く）", "orders.order_count_of_customer", "FALSE",],
            ["2", "受注管理CSV", "36", "購入回（固定）", "orders.order_count_of_customer_without_cancel", "FALSE",],
            ["2", "受注管理CSV", "37", "卸", "orders.is_wholesale", "FALSE",],
            ["2", "受注管理CSV", "38", "購入時警告", "orders.purchase_warning_flag", "FALSE",],
            ["2", "受注管理CSV", "39", "エラー表示", "orders.display_purchase_warning_flag", "FALSE",],
            ["2", "受注管理CSV", "40", "サンプルフラグ", "orders.is_sample", "FALSE",],
            ["2", "受注管理CSV", "41", "購入ルート", "orders.purchase_route_id", "FALSE",],
            ["2", "受注管理CSV", "42", "更新日時", "orders.updated_at", "FALSE",],
            ["2", "受注管理CSV", "43", "決済ベンダ", "orders.settlement_vendor", "FALSE",],
            ["2", "受注管理CSV", "44", "決済ベンダサブコード", "orders.settlement_vendor_sub_code", "FALSE",],
            ["2", "受注管理CSV", "45", "決済結果", "orders.settlement_result", "FALSE",],
            ["2", "受注管理CSV", "46", "決済番号", "orders.settlement_id", "FALSE",],
            ["3", "定期管理CSV", "1", "定期ID", "periodic_orders.id", "TRUE",],
            ["3", "定期管理CSV", "2", "顧客ID", "periodic_orders.customer_id", "TRUE",],
            ["3", "定期管理CSV", "3", "お名前(姓)", "periodic_orders.name01", "TRUE",],
            ["3", "定期管理CSV", "4", "お名前(名)", "periodic_orders.name02", "TRUE",],
            ["3", "定期管理CSV", "5", "お名前(フリガナ・姓)", "periodic_orders.kana01", "TRUE",],
            ["3", "定期管理CSV", "6", "お名前(フリガナ名)", "periodic_orders.kana02", "TRUE",],
            ["3", "定期管理CSV", "7", "郵便番号", "periodic_orders.zipcode", "TRUE",],
            ["3", "定期管理CSV", "8", "都道府県", "prefectures.name as prefecture_name", "TRUE",],
            ["3", "定期管理CSV", "9", "住所１", "periodic_orders.address01", "TRUE",],
            ["3", "定期管理CSV", "10", "住所２", "periodic_orders.address02", "TRUE",],
            ["3", "定期管理CSV", "11", "配送要望", "periodic_orders.requests_for_delivery", "TRUE",],
            ["3", "定期管理CSV", "12", "メールアドレス", "periodic_orders.email", "TRUE",],
            ["3", "定期管理CSV", "13", "電話番号1", "periodic_orders.phone_number01", "TRUE",],
            ["3", "定期管理CSV", "14", "電話番号2", "periodic_orders.phone_number02", "TRUE",],
            ["3", "定期管理CSV", "15", "要望等", "periodic_orders.message_from_customer", "TRUE",],
            ["3", "定期管理CSV", "16", "支払い方法名", "payment_methods.name as  payment_method_name", "TRUE",],
            ["3", "定期管理CSV", "17", "定期回", "periodic_orders.periodic_count", "TRUE",],
            ["3", "定期管理CSV", "18", "停止", "periodic_orders.stop_flag", "TRUE",],
            ["3", "定期管理CSV", "19", "失敗", "periodic_orders.failed_flag", "TRUE",],
            ["3", "定期管理CSV", "20", "間隔日数", "periodic_orders.interval_days", "TRUE",],
            ["3", "定期管理CSV", "21", "間隔月数", "periodic_orders.interval_month", "TRUE",],
            ["3", "定期管理CSV", "22", "間隔日付", "periodic_orders.interval_date_of_month", "TRUE",],
            ["3", "定期管理CSV", "23", "次回お届け予定", "periodic_orders.next_delivery_date", "TRUE",],
            ["3", "定期管理CSV", "24", "前回お届け", "periodic_orders.last_delivery_date", "TRUE",],
            [
                "3",
                "定期管理CSV",
                "25",
                "SHOPメモ",
                "regexp_replace((select string_agg(tmp_string, '') from (select (to_char(created_at,'YYYYMMDD HH24：MI ') || note) as tmp_string from shop_memos where shop_memos.periodic_order_id = periodic_orders.id ORDER BY created_at desc) as tmp_memo ), '\(\r\n|\r|\n|\t\)', ' ', 'g') as shop_memo",
                "TRUE",
            ],
            ["4", "配送管理CSV", "1", "受注番号", "orders.id", "TRUE",],
            ["4", "配送管理CSV", "2", "顧客ID", "orders.customer_id", "TRUE",],
            ["4", "配送管理CSV", "3", "要望等", "orders.message_from_customer", "TRUE",],
            ["4", "配送管理CSV", "4", "お客様名(姓)", "orders.name01", "TRUE",],
            ["4", "配送管理CSV", "5", "お客様名(名)", "orders.name02", "TRUE",],
            ["4", "配送管理CSV", "6", "お客様名(セイ)", "orders.kana01", "TRUE",],
            ["4", "配送管理CSV", "7", "お客様名(メイ)", "orders.kana02", "TRUE",],
            ["4", "配送管理CSV", "8", "お客様電話番号1", "orders.phone_number01", "TRUE",],
            ["4", "配送管理CSV", "9", "お客様電話番号2", "NULL as phone_number_dummy1", "TRUE",],
            ["4", "配送管理CSV", "10", "お客様電話番号3", "NULL as phone_number_dummy2", "TRUE",],
            ["4", "配送管理CSV", "11", "お客様郵便番号1", "orders.zipcode", "TRUE",],
            ["4", "配送管理CSV", "12", "お客様郵便番号2", "NULL as zipcode_dummy", "TRUE",],
            ["4", "配送管理CSV", "13", "お客様都道府県", "order_prefectures.name as order_prefecture_name", "TRUE",],
            ["4", "配送管理CSV", "14", "お客様住所1", "orders.address01", "TRUE",],
            ["4", "配送管理CSV", "15", "お客様住所2", "orders.address02", "TRUE",],
            ["4", "配送管理CSV", "16", "お届け先名(姓)", "shippings.name01 as shipping_name01", "TRUE",],
            ["4", "配送管理CSV", "17", "お届け先名(名)", "shippings.name02 as shipping_name02", "TRUE",],
            ["4", "配送管理CSV", "18", "お届け先名(セイ)", "shippings.kana01 as shipping_kana01", "TRUE",],
            ["4", "配送管理CSV", "19", "お届け先名(メイ)", "shippings.kana02 as shipping_kana02", "TRUE",],
            ["4", "配送管理CSV", "20", "お届け先電話番号1", "shippings.phone_number01 as shipping_phone_number01", "TRUE",],
            ["4", "配送管理CSV", "21", "お届け先電話番号2", "NULL as shipping_phone_number_dummy1", "TRUE",],
            ["4", "配送管理CSV", "22", "お届け先電話番号3", "NULL as shipping_phone_number_dummy2", "TRUE",],
            ["4", "配送管理CSV", "23", "お届け先郵便番号1", "shippings.zipcode as shipping_zipcode", "TRUE",],
            ["4", "配送管理CSV", "24", "お届け先郵便番号2", "NULL as shipping_zipcode_dummy", "TRUE",],
            ["4", "配送管理CSV", "25", "お届け先都道府県", "shipping_prefectures.name as shippping_prefecture_name", "TRUE",],
            ["4", "配送管理CSV", "26", "お届け先住所1", "shippings.address01 as shipping_addres01", "TRUE",],
            ["4", "配送管理CSV", "27", "お届け先住所2", "shippings.address02 as shipping_addres02", "TRUE",],
            [
                "4",
                "配送管理CSV",
                "28",
                "小計",
                "bundled_order_summary.subtotal + bundled_order_summary.subtotal_tax as subtotal",
                "TRUE",
            ],
            ["4", "配送管理CSV", "29", "単価", "bundled_order_detail.price", "TRUE",],
            ["4", "配送管理CSV", "30", "値引", "bundled_order_summary.discount as discount", "TRUE",],
            [
                "4",
                "配送管理CSV",
                "31",
                "送料",
                "bundled_order_summary.delivery_fee + bundled_order_summary.delivery_fee_tax as delivery_fee",
                "TRUE",
            ],
            [
                "4",
                "配送管理CSV",
                "32",
                "手数料",
                "bundled_order_summary.payment_method_fee + bundled_order_summary.payment_method_fee_tax as payment_method_fee",
                "TRUE",
            ],
            ["4", "配送管理CSV", "33", "消費税額", "bundled_order_summary.payment_total_tax as tax", "TRUE",],
            [
                "4",
                "配送管理CSV",
                "34",
                "支払金額",
                "bundled_order_summary.payment_total + bundled_order_summary.payment_total_tax as payment_total",
                "TRUE",
            ],
            ["4", "配送管理CSV", "35", "支払方法", "orders.payment_method_name", "TRUE",],
            ["4", "配送管理CSV", "36", "配送指定日", "shippings.requested_delivery_date", "TRUE",],
            ["4", "配送管理CSV", "37", "配送指定時間", "shippings.delivery_time_name", "TRUE",],
            ["4", "配送管理CSV", "38", "購入回数", "customers.buy_times", "TRUE",],
            ["4", "配送管理CSV", "39", "贈答フラグ", "NULL as gift_flag", "TRUE",],
            ["4", "配送管理CSV", "40", "カードメッセージ", "NULL as card_message", "TRUE",],
            ["4", "配送管理CSV", "41", "商品名", "bundled_order_detail.product_name", "TRUE",],
            ["4", "配送管理CSV", "42", "商品コード", "bundled_order_detail.product_code", "TRUE",],
            ["4", "配送管理CSV", "43", "数量", "bundled_order_detail.quantity", "TRUE",],
            ["4", "配送管理CSV", "44", "発送日", "shippings.shipped_timestamp", "TRUE",],
            ["4", "配送管理CSV", "45", "ご注文日", "orders.created_at", "TRUE",],
            ["4", "配送管理CSV", "46", "梱包", "NULL as packaging_name", "TRUE",],
            ["4", "配送管理CSV", "47", "配送方法", "orders.delivery_name", "TRUE",],
            [
                "4",
                "配送管理CSV",
                "48",
                "定期お届け間隔",
                "CASE WHEN products.is_periodic THEN CASE original_periodic_orders.periodic_interval_type_id WHEN 1 THEN to_char(original_periodic_orders.interval_days,'999') WHEN 2 THEN to_char(original_periodic_orders.interval_month,'9') || 'ヶ月毎' || to_char(original_periodic_orders.interval_days,'99') || '日' END ELSE NULL END as periodic_interval",
                "TRUE",
            ],
            [
                "4",
                "配送管理CSV",
                "49",
                "次回到着予定日",
                "CASE WHEN products.is_periodic THEN original_periodic_orders.next_delivery_date ELSE NULL END as periodic_next_delivery_date",
                "TRUE",
            ],
            ["4", "配送管理CSV", "50", "伝票番号", "shippings.delivery_slip_num", "TRUE",],
            ["4", "配送管理CSV", "51", "広告番号", "customers.advertising_media_code", "TRUE",],
            ["10", "購入不可設定CSV", "1", "設定ID", "product_purchase_warnings.id", "TRUE",],
            ["10", "購入不可設定CSV", "2", "商品ID", "products.id as product_id", "TRUE",],
            ["10", "購入不可設定CSV", "3", "商品名", "products.name as product_name", "TRUE",],
            ["10", "購入不可設定CSV", "4", "商品コード", "products.code as product_code", "TRUE",],
            ["10", "購入不可設定CSV", "5", "購入不可商品ID", "products_to_warn.id product_id_to_warn", "TRUE",],
            ["10", "購入不可設定CSV", "6", "購入不可商品名", "products_to_warn.name product_name_to_warn", "TRUE",],
            ["10", "購入不可設定CSV", "7", "購入不可商品コード", "products_to_warn.code as product_code_to_warn", "TRUE",],
            ["11", "購入時警告対象設定CSV", "1", "設定ID", "product_purchase_warnings.id", "TRUE",],
            ["11", "購入時警告対象設定CSV", "2", "商品ID", "products.id as product_id", "TRUE",],
            ["11", "購入時警告対象設定CSV", "3", "商品名", "products.name as product_name", "TRUE",],
            ["11", "購入時警告対象設定CSV", "4", "商品コード", "products.code as product_code", "TRUE",],
            ["11", "購入時警告対象設定CSV", "5", "警告対象商品ID", "products_to_warn.id product_id_to_warn", "TRUE",],
            ["11", "購入時警告対象設定CSV", "6", "警告対象商品名", "products_to_warn.name product_name_to_warn", "TRUE",],
            ["11", "購入時警告対象設定CSV", "7", "警告対象商品コード", "products_to_warn.code as product_code_to_warn", "TRUE",],
            ["12", "定期同梱物設定", "1", "同梱設定ID", "item_bundle_settings.id", "TRUE",],
            ["12", "定期同梱物設定", "2", "対象商品ID", "item_bundle_settings.req_product_id", "TRUE",],
            ["12", "定期同梱物設定", "3", "対象商品名", "req_products.name as req_product_name", "TRUE",],
            ["12", "定期同梱物設定", "4", "対象商品コード", "req_products.code as req_product_code", "TRUE",],
            ["12", "定期同梱物設定", "5", "同梱商品ID", "item_bundle_settings.product_id", "TRUE",],
            ["12", "定期同梱物設定", "6", "同梱商品名", "products.name as product_name", "TRUE",],
            ["12", "定期同梱物設定", "7", "同梱商品コード", "products.code as product_code", "TRUE",],
            ["12", "定期同梱物設定", "8", "対象定期回", "item_bundle_settings.req_periodic_count", "TRUE",],
            ["12", "定期同梱物設定", "9", "設定", "item_bundle_settings.enabled", "TRUE",],
            ["13", "広告媒体CSV", "1", "広告番号", "advertising_media.code", "TRUE",],
            ["13", "広告媒体CSV", "2", "媒体名", "advertising_media.name", "TRUE",],
            ["13", "広告媒体CSV", "3", "媒体種別", "medium_types.name as media_type_name", "TRUE",],
            ["13", "広告媒体CSV", "4", "エリア", "advertising_media.area", "TRUE",],
            ["13", "広告媒体CSV", "5", "広告日", "advertising_media.date", "TRUE",],
            ["13", "広告媒体CSV", "6", "開始時間", "advertising_media.start_time", "TRUE",],
            ["13", "広告媒体CSV", "7", "広告費", "advertising_media.cost", "TRUE",],
            ["13", "広告媒体CSV", "8", "ラインナップ", "item_lineups.name as item_lineup_name", "TRUE",],
            ["13", "広告媒体CSV", "9", "備考", "advertising_media.remark", "TRUE",],
            ["13", "広告媒体CSV", "10", "部数", "advertising_media.circulation", "TRUE",],
            ["13", "広告媒体CSV", "11", "媒体詳細", "advertising_media.detail", "TRUE",],
            ["13", "広告媒体CSV", "12", "放送局", "advertising_media.broadcaster", "TRUE",],
            ["13", "広告媒体CSV", "13", "放送時間分数", "advertising_media.broadcast_minutes", "TRUE",],
            ["13", "広告媒体CSV", "14", "放送枠", "advertising_media.broadcast_duration_from", "TRUE",],
            ["13", "広告媒体CSV", "15", "放送枠", "advertising_media.broadcast_duration_to", "TRUE",],
            ["13", "広告媒体CSV", "16", "コール予測数", "advertising_media.call_expected", "TRUE",],
            ["14", "ステップDMCSV", "1", "注文ID", "stepdm_history_details.order_id", "TRUE",],
            ["14", "ステップDMCSV", "2", "DMID", "stepdm_history_details.stepdm_setting_id", "TRUE",],
            ["14", "ステップDMCSV", "3", "DM コード", "stepdm_history_details.stepdm_setting_code", "TRUE",],
            ["14", "ステップDMCSV", "4", "姓", "stepdm_history_details.order_name01", "TRUE",],
            ["14", "ステップDMCSV", "5", "名", "stepdm_history_details.order_name02", "TRUE",],
            ["14", "ステップDMCSV", "6", "セイ", "stepdm_history_details.order_kana01", "TRUE",],
            ["14", "ステップDMCSV", "7", "メイ", "stepdm_history_details.order_kana02", "TRUE",],
            [
                "14",
                "ステップDMCSV",
                "8",
                "郵便番号1",
                "substring(stepdm_history_details.order_zipcode,1,3) as order_zipcode01",
                "TRUE",
            ],
            [
                "14",
                "ステップDMCSV",
                "9",
                "郵便番号2",
                "substring(stepdm_history_details.order_zipcode,4) as order_zipcode02",
                "TRUE",
            ],
            ["14", "ステップDMCSV", "10", "都道府県", "prefectures.name as prefecture_name", "TRUE",],
            ["14", "ステップDMCSV", "11", "住所1", "stepdm_history_details.order_address01", "TRUE",],
            ["14", "ステップDMCSV", "12", "住所2_1", "substring(stepdm_history_details.order_address02,1,32) as order_address02_1", "TRUE",],
            ["14", "ステップDMCSV", "13", "住所2_2", "substring(stepdm_history_details.order_address02,33) as order_address02_2", "TRUE",],
            ["14", "ステップDMCSV", "14", "電話番号", "stepdm_history_details.order_phone_number01", "TRUE",],
            ["14", "ステップDMCSV", "15", "ファイル出力日", "to_char(now(),'YYYY/MM/DD') as now_date", "TRUE",],
            ["15", "マーケ部門サマリー", "1", "集計日時", "marketing_summary_batch_logs.created_at", "TRUE",],
            ["15", "マーケ部門サマリー", "2", "集計期間", "marketing_summary_batch_logs.period_from", "TRUE",],
            ["15", "マーケ部門サマリー", "3", "集計期間", "marketing_summary_batch_logs.period_to", "TRUE",],
            ["15", "マーケ部門サマリー", "4", "新規", "marketing_summary_batch_logs.sales_of_first", "TRUE",],
            ["15", "マーケ部門サマリー", "5", "リピート", "marketing_summary_batch_logs.sales_of_repeat", "TRUE",],
            ["15", "マーケ部門サマリー", "6", "合計", "marketing_summary_batch_logs.sales", "TRUE",],
            ["15", "マーケ部門サマリー", "7", "顧客数", "marketing_summary_batch_logs.customer_count", "TRUE",],
            ["15", "マーケ部門サマリー", "8", "受注数", "marketing_summary_batch_logs.order_count", "TRUE",],
            ["15", "マーケ部門サマリー", "9", "平均単価", "marketing_summary_batch_logs.average_unit_price", "TRUE",],

        ];

        foreach ($data as $key => $record) {
            $model = new CsvOutputSetting();
            $model->id = $key+1;
            $model->csv_type_id = $record[0];
            $model->col = $record[4];
            $model->item_name = $record[3];
            $model->rank = $record[2];
            $model->enabled = $record[5];
            $model->save();

        }
    }
}
